[project]
name = "pyollamachat"
version = "0.1.0"
description = "A chat application for ollama made with python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.8",
]
